# BPGE1

[[NamedAnchors]]
Name = '''scripts.newgame.starters.left'''
Address = 0x169C09
Format = '''[species1:data.pokemon.names]scripts.newgame.starters.middle'''

[[NamedAnchors]]
Name = '''scripts.newgame.starters.middle'''
Address = 0x169DD6
Format = '''[species2:data.pokemon.names]1'''

[[NamedAnchors]]
Name = '''scripts.newgame.starters.right'''
Address = 0x169E0C
Format = '''[species3:data.pokemon.names]scripts.newgame.starters.middle'''
