
[[NamedAnchors]]
Name = '''data.header.romname'''
Address = 0x000108
Format = '''`asc`32'''

[[NamedAnchors]]
Name = '''sound.newgame.titlescreen.song'''
Address = 0x0AAAE8
Format = '''[track::songnames]1'''

[[OffsetPointer]]
Address = 0x038850
Offset = 0x000004

[[OffsetPointer]]
Address = 0x0389F8
Offset = 0x000004

[[OffsetPointer]]
Address = 0x069188
Offset = 0x000004

[[OffsetPointer]]
Address = 0x069230
Offset = 0x000004

[[OffsetPointer]]
Address = 0x06B82C
Offset = 0x000004

[[List]]
Name = '''pokenavTowns'''
0 = [
   '''LITTLEROOT TOWN''',
   '''OLDALE TOWN''',
   '''DEWFORD TOWN''',
   '''LAVARIDGE TOWN''',
   '''FALLARBOR TOWN''',
   '''VERDANTURF TOWN''',
   '''PACIFIDLOG TOWN''',
   '''PETALBURG CITY''',
   '''SLATEPORT CITY TOP''',
   '''SLATEPORT CITY BOTTOM''',
   '''MAUVILLE CITY LEFT''',
   '''MAUVILLE CITY RIGHT''',
   '''RUSTBORO CITY TOP''',
   '''RUSTBORO CITY BOTTOM''',
   '''FORTREE CITY''',
   '''LILYCOVE CITY LEFT''',
   '''LILYCOVE CITY RIGHT''',
   '''MOSSDEEP CITY LEFT''',
   '''MOSSDEEP CITY RIGHT''',
   '''SOOTOPOLIS CITY''',
   '''EVER GRANDE CITY TOP''',
   '''EVER GRANDE CITY BOTTOM''',
]

[[List]]
Name = '''songnames'''
0 = [
   '''mus_dummy''',
   '''se_use_item''',
   '''se_pc_login''',
   '''se_pc_off''',
   '''se_pc_on''',
   '''se_select''',
   '''se_win_open''',
   '''se_wall_hit''',
   '''se_door''',
   '''se_exit''',
   '''se_ledge''',
   '''se_bike_bell''',
   '''se_not_effective''',
   '''se_effective''',
   '''se_super_effective''',
   '''se_ball_open''',
   '''se_faint''',
   '''se_flee''',
   '''se_sliding_door''',
   '''se_ship''',
   '''se_bang''',
   '''se_pin''',
   '''se_boo''',
   '''se_ball''',
   '''se_contest_place''',
   '''se_a''',
   '''se_i''',
   '''se_u''',
   '''se_e''',
   '''se_o''',
   '''se_n''',
   '''se_success''',
   '''se_failure''',
   '''se_exp''',
   '''se_bike_hop''',
   '''se_switch''',
   '''se_click''',
   '''se_fu_zaku''',
   '''se_contest_condition_lose''',
   '''se_lavaridge_fall_warp''',
   '''se_ice_stairs''',
   '''se_ice_break''',
   '''se_ice_crack''',
   '''se_fall''',
   '''se_unlock''',
   '''se_warp_in''',
   '''se_warp_out''',
   '''se_repel''',
   '''se_rotating_gate''',
   '''se_truck_move''',
   '''se_truck_stop''',
   '''se_truck_unload''',
   '''se_truck_door''',
   '''se_berry_blender''',
   '''se_card''',
   '''se_save''',
   '''se_ball_bounce_1''',
   '''se_ball_bounce_2''',
   '''se_ball_bounce_3''',
   '''se_ball_bounce_4''',
   '''se_ball_trade''',
   '''se_ball_throw''',
   '''se_note_c''',
   '''se_note_d''',
   '''se_note_e''',
   '''se_note_f''',
   '''se_note_g''',
   '''se_note_a''',
   '''se_note_b''',
   '''se_note_c_high''',
   '''se_puddle''',
   '''se_bridge_walk''',
   '''se_itemfinder''',
   '''se_ding_dong''',
   '''se_balloon_red''',
   '''se_balloon_blue''',
   '''se_balloon_yellow''',
   '''se_breakable_door''',
   '''se_mud_ball''',
   '''se_field_poison''',
   '''se_escalator''',
   '''se_thunderstorm''',
   '''se_thunderstorm_stop''',
   '''se_downpour''',
   '''se_downpour_stop''',
   '''se_rain''',
   '''se_rain_stop''',
   '''se_thunder''',
   '''se_thunder2''',
   '''se_elevator''',
   '''se_low_health''',
   '''se_exp_max''',
   '''se_roulette_ball''',
   '''se_roulette_ball2''',
   '''se_taillow_wing_flap''',
   '''se_shop''',
   '''se_contest_heart''',
   '''se_contest_curtain_rise''',
   '''se_contest_curtain_fall''',
   '''se_contest_icon_change''',
   '''se_contest_icon_clear''',
   '''se_contest_mons_turn''',
   '''se_shiny''',
   '''se_intro_blast''',
   '''se_mugshot''',
   '''se_applause''',
   '''se_vend''',
   '''se_orb''',
   '''se_dex_scroll''',
   '''se_dex_page''',
   '''se_pokenav_on''',
   '''se_pokenav_off''',
   '''se_dex_search''',
   '''se_egg_hatch''',
   '''se_ball_tray_enter''',
   '''se_ball_tray_ball''',
   '''se_ball_tray_exit''',
   '''se_glass_flute''',
   '''se_m_thunderbolt''',
   '''se_m_thunderbolt2''',
   '''se_m_harden''',
   '''se_m_nightmare''',
   '''se_m_vital_throw''',
   '''se_m_vital_throw2''',
   '''se_m_bubble''',
   '''se_m_bubble2''',
   '''se_m_bubble3''',
   '''se_m_rain_dance''',
   '''se_m_cut''',
   '''se_m_string_shot''',
   '''se_m_string_shot2''',
   '''se_m_rock_throw''',
   '''se_m_gust''',
   '''se_m_gust2''',
   '''se_m_double_slap''',
   '''se_m_double_team''',
   '''se_m_razor_wind''',
   '''se_m_icy_wind''',
   '''se_m_thunder_wave''',
   '''se_m_comet_punch''',
   '''se_m_mega_kick''',
   '''se_m_mega_kick2''',
   '''se_m_crabhammer''',
   '''se_m_jump_kick''',
   '''se_m_flame_wheel''',
   '''se_m_flame_wheel2''',
   '''se_m_flamethrower''',
   '''se_m_fire_punch''',
   '''se_m_toxic''',
   '''se_m_sacred_fire''',
   '''se_m_sacred_fire2''',
   '''se_m_ember''',
   '''se_m_take_down''',
   '''se_m_blizzard''',
   '''se_m_blizzard2''',
   '''se_m_scratch''',
   '''se_m_vicegrip''',
   '''se_m_wing_attack''',
   '''se_m_fly''',
   '''se_m_sand_attack''',
   '''se_m_razor_wind2''',
   '''se_m_bite''',
   '''se_m_headbutt''',
   '''se_m_surf''',
   '''se_m_hydro_pump''',
   '''se_m_whirlpool''',
   '''se_m_horn_attack''',
   '''se_m_tail_whip''',
   '''se_m_mist''',
   '''se_m_poison_powder''',
   '''se_m_bind''',
   '''se_m_dragon_rage''',
   '''se_m_sing''',
   '''se_m_perish_song''',
   '''se_m_pay_day''',
   '''se_m_dig''',
   '''se_m_dizzy_punch''',
   '''se_m_self_destruct''',
   '''se_m_explosion''',
   '''se_m_absorb_2''',
   '''se_m_absorb''',
   '''se_m_screech''',
   '''se_m_bubble_beam''',
   '''se_m_bubble_beam2''',
   '''se_m_supersonic''',
   '''se_m_belly_drum''',
   '''se_m_metronome''',
   '''se_m_bonemerang''',
   '''se_m_lick''',
   '''se_m_psybeam''',
   '''se_m_faint_attack''',
   '''se_m_swords_dance''',
   '''se_m_leer''',
   '''se_m_swagger''',
   '''se_m_swagger2''',
   '''se_m_heal_bell''',
   '''se_m_confuse_ray''',
   '''se_m_snore''',
   '''se_m_brick_break''',
   '''se_m_giga_drain''',
   '''se_m_psybeam2''',
   '''se_m_solar_beam''',
   '''se_m_petal_dance''',
   '''se_m_teleport''',
   '''se_m_minimize''',
   '''se_m_sketch''',
   '''se_m_swift''',
   '''se_m_reflect''',
   '''se_m_barrier''',
   '''se_m_detect''',
   '''se_m_lock_on''',
   '''se_m_moonlight''',
   '''se_m_charm''',
   '''se_m_charge''',
   '''se_m_strength''',
   '''se_m_hyper_beam''',
   '''se_m_waterfall''',
   '''se_m_reversal''',
   '''se_m_acid_armor''',
   '''se_m_sandstorm''',
   '''se_m_tri_attack''',
   '''se_m_tri_attack2''',
   '''se_m_encore''',
   '''se_m_encore2''',
   '''se_m_baton_pass''',
   '''se_m_milk_drink''',
   '''se_m_attract''',
   '''se_m_attract2''',
   '''se_m_morning_sun''',
   '''se_m_flatter''',
   '''se_m_sand_tomb''',
   '''se_m_grasswhistle''',
   '''se_m_spit_up''',
   '''se_m_dive''',
   '''se_m_earthquake''',
   '''se_m_twister''',
   '''se_m_sweet_scent''',
   '''se_m_yawn''',
   '''se_m_sky_uppercut''',
   '''se_m_stat_increase''',
   '''se_m_heat_wave''',
   '''se_m_uproar''',
   '''se_m_hail''',
   '''se_m_cosmic_power''',
   '''se_m_teeter_dance''',
   '''se_m_stat_decrease''',
   '''se_m_haze''',
   '''se_m_hyper_beam2''',
   '''se_rg_door''',
   '''se_rg_card_flip''',
   '''se_rg_card_flipping''',
   '''se_rg_card_open''',
   '''se_rg_bag_cursor''',
   '''se_rg_bag_pocket''',
   '''se_rg_ball_click''',
   '''se_rg_shop''',
   '''se_rg_ss_anne_horn''',
   '''se_rg_help_open''',
   '''se_rg_help_close''',
   '''se_rg_help_error''',
   '''se_rg_deoxys_move''',
   '''se_rg_poke_jump_success''',
   '''se_rg_poke_jump_failure''',
   '''se_pokenav_call''',
   '''se_pokenav_hang_up''',
   '''se_arena_timeup1''',
   '''se_arena_timeup2''',
   '''se_pike_curtain_close''',
   '''se_pike_curtain_open''',
   '''se_sudowoodo_shake''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''dummy_song_header''',
   '''mus_littleroot_test''',
   '''mus_gsc_route38''',
   '''mus_caught''',
   '''mus_victory_wild''',
   '''mus_victory_gym_leader''',
   '''mus_victory_league''',
   '''mus_c_comm_center''',
   '''mus_gsc_pewter''',
   '''mus_c_vs_legend_beast''',
   '''mus_route101''',
   '''mus_route110''',
   '''mus_route120''',
   '''mus_petalburg''',
   '''mus_oldale''',
   '''mus_gym''',
   '''mus_surf''',
   '''mus_petalburg_woods''',
   '''mus_level_up''',
   '''mus_heal''',
   '''mus_obtain_badge''',
   '''mus_obtain_item''',
   '''mus_evolved''',
   '''mus_obtain_tmhm''',
   '''mus_lilycove_museum''',
   '''mus_route122''',
   '''mus_oceanic_museum''',
   '''mus_evolution_intro''',
   '''mus_evolution''',
   '''mus_move_deleted''',
   '''mus_encounter_girl''',
   '''mus_encounter_male''',
   '''mus_abandoned_ship''',
   '''mus_fortree''',
   '''mus_birch_lab''',
   '''mus_b_tower_rs''',
   '''mus_encounter_swimmer''',
   '''mus_cave_of_origin''',
   '''mus_obtain_berry''',
   '''mus_awaken_legend''',
   '''mus_slots_jackpot''',
   '''mus_slots_win''',
   '''mus_too_bad''',
   '''mus_roulette''',
   '''mus_link_contest_p1''',
   '''mus_link_contest_p2''',
   '''mus_link_contest_p3''',
   '''mus_link_contest_p4''',
   '''mus_encounter_rich''',
   '''mus_verdanturf''',
   '''mus_rustboro''',
   '''mus_poke_center''',
   '''mus_route104''',
   '''mus_route119''',
   '''mus_cycling''',
   '''mus_poke_mart''',
   '''mus_littleroot''',
   '''mus_mt_chimney''',
   '''mus_encounter_female''',
   '''mus_lilycove''',
   '''mus_route111''',
   '''mus_help''',
   '''mus_underwater''',
   '''mus_victory_trainer''',
   '''mus_title''',
   '''mus_intro''',
   '''mus_encounter_may''',
   '''mus_encounter_intense''',
   '''mus_encounter_cool''',
   '''mus_route113''',
   '''mus_encounter_aqua''',
   '''mus_follow_me''',
   '''mus_encounter_brendan''',
   '''mus_ever_grande''',
   '''mus_encounter_suspicious''',
   '''mus_victory_aqua_magma''',
   '''mus_cable_car''',
   '''mus_game_corner''',
   '''mus_dewford''',
   '''mus_safari_zone''',
   '''mus_victory_road''',
   '''mus_aqua_magma_hideout''',
   '''mus_sailing''',
   '''mus_mt_pyre''',
   '''mus_slateport''',
   '''mus_mt_pyre_exterior''',
   '''mus_school''',
   '''mus_hall_of_fame''',
   '''mus_fallarbor''',
   '''mus_sealed_chamber''',
   '''mus_contest_winner''',
   '''mus_contest''',
   '''mus_encounter_magma''',
   '''mus_intro_battle''',
   '''mus_abnormal_weather''',
   '''mus_weather_groudon''',
   '''mus_sootopolis''',
   '''mus_contest_results''',
   '''mus_hall_of_fame_room''',
   '''mus_trick_house''',
   '''mus_encounter_twins''',
   '''mus_encounter_elite_four''',
   '''mus_encounter_hiker''',
   '''mus_contest_lobby''',
   '''mus_encounter_interviewer''',
   '''mus_encounter_champion''',
   '''mus_credits''',
   '''mus_end''',
   '''mus_b_frontier''',
   '''mus_b_arena''',
   '''mus_obtain_b_points''',
   '''mus_register_match_call''',
   '''mus_b_pyramid''',
   '''mus_b_pyramid_top''',
   '''mus_b_palace''',
   '''mus_rayquaza_appears''',
   '''mus_b_tower''',
   '''mus_obtain_symbol''',
   '''mus_b_dome''',
   '''mus_b_pike''',
   '''mus_b_factory''',
   '''mus_vs_rayquaza''',
   '''mus_vs_frontier_brain''',
   '''mus_vs_mew''',
   '''mus_b_dome_lobby''',
   '''mus_vs_wild''',
   '''mus_vs_aqua_magma''',
   '''mus_vs_trainer''',
   '''mus_vs_gym_leader''',
   '''mus_vs_champion''',
   '''mus_vs_regi''',
   '''mus_vs_kyogre_groudon''',
   '''mus_vs_rival''',
   '''mus_vs_elite_four''',
   '''mus_vs_aqua_magma_leader''',
   '''mus_rg_follow_me''',
   '''mus_rg_game_corner''',
   '''mus_rg_rocket_hideout''',
   '''mus_rg_gym''',
   '''mus_rg_jigglypuff''',
   '''mus_rg_intro_fight''',
   '''mus_rg_title''',
   '''mus_rg_cinnabar''',
   '''mus_rg_lavender''',
   '''mus_rg_heal''',
   '''mus_rg_cycling''',
   '''mus_rg_encounter_rocket''',
   '''mus_rg_encounter_girl''',
   '''mus_rg_encounter_boy''',
   '''mus_rg_hall_of_fame''',
   '''mus_rg_viridian_forest''',
   '''mus_rg_mt_moon''',
   '''mus_rg_poke_mansion''',
   '''mus_rg_credits''',
   '''mus_rg_route1''',
   '''mus_rg_route24''',
   '''mus_rg_route3''',
   '''mus_rg_route11''',
   '''mus_rg_victory_road''',
   '''mus_rg_vs_gym_leader''',
   '''mus_rg_vs_trainer''',
   '''mus_rg_vs_wild''',
   '''mus_rg_vs_champion''',
   '''mus_rg_pallet''',
   '''mus_rg_oak_lab''',
   '''mus_rg_oak''',
   '''mus_rg_poke_center''',
   '''mus_rg_ss_anne''',
   '''mus_rg_surf''',
   '''mus_rg_poke_tower''',
   '''mus_rg_silph''',
   '''mus_rg_fuchsia''',
   '''mus_rg_celadon''',
   '''mus_rg_victory_trainer''',
   '''mus_rg_victory_wild''',
   '''mus_rg_victory_gym_leader''',
   '''mus_rg_vermillion''',
   '''mus_rg_pewter''',
   '''mus_rg_encounter_rival''',
   '''mus_rg_rival_exit''',
   '''mus_rg_dex_rating''',
   '''mus_rg_obtain_key_item''',
   '''mus_rg_caught_intro''',
   '''mus_rg_photo''',
   '''mus_rg_game_freak''',
   '''mus_rg_caught''',
   '''mus_rg_new_game_instruct''',
   '''mus_rg_new_game_intro''',
   '''mus_rg_new_game_exit''',
   '''mus_rg_poke_jump''',
   '''mus_rg_union_room''',
   '''mus_rg_net_center''',
   '''mus_rg_mystery_gift''',
   '''mus_rg_berry_pick''',
   '''mus_rg_sevii_cave''',
   '''mus_rg_teachy_tv_show''',
   '''mus_rg_sevii_route''',
   '''mus_rg_sevii_dungeon''',
   '''mus_rg_sevii_123''',
   '''mus_rg_sevii_45''',
   '''mus_rg_sevii_67''',
   '''mus_rg_poke_flute''',
   '''mus_rg_vs_deoxys''',
   '''mus_rg_vs_mewtwo''',
   '''mus_rg_vs_legend''',
   '''mus_rg_encounter_gym_leader''',
   '''mus_rg_encounter_deoxys''',
   '''mus_rg_trainer_tower''',
   '''mus_rg_slow_pallet''',
   '''mus_rg_teachy_tv_menu''',
   '''ph_trap_blend''',
   '''ph_trap_held''',
   '''ph_trap_solo''',
   '''ph_face_blend''',
   '''ph_face_held''',
   '''ph_face_solo''',
   '''ph_cloth_blend''',
   '''ph_cloth_held''',
   '''ph_cloth_solo''',
   '''ph_dress_blend''',
   '''ph_dress_held''',
   '''ph_dress_solo''',
   '''ph_fleece_blend''',
   '''ph_fleece_held''',
   '''ph_fleece_solo''',
   '''ph_kit_blend''',
   '''ph_kit_held''',
   '''ph_kit_solo''',
   '''ph_price_blend''',
   '''ph_price_held''',
   '''ph_price_solo''',
   '''ph_lot_blend''',
   '''ph_lot_held''',
   '''ph_lot_solo''',
   '''ph_goat_blend''',
   '''ph_goat_held''',
   '''ph_goat_solo''',
   '''ph_thought_blend''',
   '''ph_thought_held''',
   '''ph_thought_solo''',
   '''ph_choice_blend''',
   '''ph_choice_held''',
   '''ph_choice_solo''',
   '''ph_mouth_blend''',
   '''ph_mouth_held''',
   '''ph_mouth_solo''',
   '''ph_foot_blend''',
   '''ph_foot_held''',
   '''ph_foot_solo''',
   '''ph_goose_blend''',
   '''ph_goose_held''',
   '''ph_goose_solo''',
   '''ph_strut_blend''',
   '''ph_strut_held''',
   '''ph_strut_solo''',
   '''ph_cure_blend''',
   '''ph_cure_held''',
   '''ph_cure_solo''',
   '''ph_nurse_blend''',
   '''ph_nurse_held''',
   '''ph_nurse_solo''',
]

[[GotoShortcut]]
Name = '''Pokemon'''
Image = '''graphics.pokemon.sprites.front/295/sprite/'''
Destination = '''data.pokemon.stats/1'''

[[GotoShortcut]]
Name = '''Trainers'''
Image = '''graphics.trainers.sprites.front/3/sprite/'''
Destination = '''data.trainers.stats'''

[[GotoShortcut]]
Name = '''Moves'''
Image = '''graphics.items.sprites/298/sprite/'''
Destination = '''data.pokemon.moves.stats.battle'''

[[GotoShortcut]]
Name = '''Items'''
Image = '''graphics.items.sprites/13/sprite/'''
Destination = '''data.items.stats'''
