[[NamedAnchors]]
Name = '''data.header.title'''
Address = 0x0000A0
Format = '''`asc`12'''

[[NamedAnchors]]
Name = '''data.header.gamecode'''
Address = 0x0000AC
Format = '''`asc`4'''

[[NamedAnchors]]
Name = '''data.header.makercode'''
Address = 0x0000B0
Format = '''`asc`2'''

[[TableGroup]]
Name = '''Pokemon'''
0 = [
   '''data.pokemon.names''',
   '''data.pokemon.stats''',
   '''data.pokemon.evolutions''',
   '''data.pokedex.regional''',
   '''data.pokedex.national''',
   '''data.pokedex.hoennToNational''',
   '''data.pokedex.search.alpha''',
   '''data.pokedex.search.weight''',
   '''data.pokedex.search.size''',
   '''data.pokedex.search.type''',
   '''sound.pokemon.cry.growl''',
   '''sound.pokemon.cry.normal''',
   '''sound.pokemon.cry.hoennconversion''',
]

[[TableGroup]]
Name = '''Sprites'''
0 = [
   '''graphics.pokemon.sprites.front''',
   '''graphics.pokemon.sprites.coordinates.front''',
   '''graphics.pokemon.animations.front''',
   '''graphics.pokemon.sprites.back''',
   '''graphics.pokemon.sprites.coordinates.back''',
   '''graphics.pokemon.animations.back''',
   '''graphics.pokemon.palettes.normal''',
   '''graphics.pokemon.palettes.shiny''',
   '''graphics.pokemon.icons.sprites''',
   '''graphics.pokemon.icons.index''',
   '''graphics.pokemon.sprites.elevation''',
   '''graphics.pokemon.sprites.anchor''',
   '''graphics.pokemon.animations.frames''',
   '''graphics.pokemon.sprites.footprint''',
]

[[TableGroup]]
Name = '''Moves'''
0 = [
   '''data.pokemon.moves.levelup''',
   '''data.pokemon.moves.tutorcompatibility''',
   '''data.pokemon.moves.tmcompatibility''',
]

[[TableGroup]]
Name = '''Trainer'''
0 = [
   '''data.trainers.stats|0''',
]

[[TableGroup]]
Name = '''Team'''
0 = [
   '''data.trainers.stats|1''',
]

[[TableGroup]]
Name = '''Move'''
0 = [
   '''data.pokemon.moves.names''',
   '''data.pokemon.moves.descriptions''',
   '''graphics.pokemon.moves.animations''',
   '''data.pokemon.moves.stats.contest''',
]

[[TableGroup]]
Name = '''Battle'''
0 = [
   '''data.pokemon.moves.stats.battle''',
]

[[TableGroup]]
Name = '''Stats'''
0 = [
   '''data.items.stats''',
]

[[TableGroup]]
Name = '''More'''
0 = [
   '''graphics.items.sprites''',
   '''data.items.effects''',
]

[[TableGroup]]
Name = '''Background'''
0 = [
   '''graphics.battle.background.sprites|0'''
]

[[TableGroup]]
Name = '''Intro'''
0 = [
   '''graphics.battle.background.sprites|1'''
]

[[List]]
Name = '''egggroups'''
0 = [
   '''None''',
   '''Monster''',
   '''Water1''',
   '''Bug''',
   '''Flying''',
   '''Field''',
   '''Fairy''',
   '''Grass''',
   '''Human-Like''',
   '''Water3''',
   '''Mineral''',
   '''Amorphous''',
   '''Water2''',
   '''Ditto''',
   '''Dragon''',
   '''Undiscovered''',
]

[[List]]
Name = '''terrains'''
0 = [
    '''grass''',
    '''long grass''',
    '''sand''',
    '''underwater''',
    '''water''',
    '''pond water''',
    '''rock''',
    '''cave''',
    '''building''',
    '''plain''',
]

[[List]]
Name = '''growthrates'''
0 = [
   '''Medium Fast''',
   '''Erratic''',
   '''Fluctuating''',
   '''Medium Slow''',
   '''Fast''',
   '''Slow''',
]

[[List]]
Name = '''bodycolors'''
0 = [
   '''Red''',
   '''Blue''',
   '''Yellow''',
   '''Green''',
   '''Black''',
   '''Brown''',
   '''Purple''',
   '''Gray''',
   '''White''',
   '''Pink''',
]

[[List]]
Name = '''effectiveness'''
0 = '''None'''
5 = '''Half'''
10 = '''Normal'''
20 = '''Double'''

[[List]]
Name = '''contesteffectnames'''
0 = [
    '''HighlyAppealing''',
    '''UserMoreEasilyStartled''',
    '''GreatAppealButNoMoreMoves''',
    '''RepetitionNotBoring''',
    '''AvoidStartleOnce''',
    '''AvoidStartle''',
    '''AvoidStartleSlightly''',
    '''UserLessEasilyStartled''',
    '''StartleFrontMon''',
    '''SlightlyStartlePrevMons''',
    '''StartlePrevMon''',
    '''StartlePrevMons''',
    '''BadlyStartleFrontMon''',
    '''BadlyStartlePrevMons''',
    '''StartlePrevMon2''',
    '''StartPrevMons2''',
    '''ShiftJudgeAttention''',
    '''StartleMonWithJudgesAttention''',
    '''JamsOthersButMissOneTurn''',
    '''StartleMonsSameTypeAppeal''',
    '''StartMonsCoolAppeal''',
    '''StartleMonsBeautyAppeal''',
    '''StartleMonsCuteAppeal''',
    '''StartleMonsSmartAppeal''',
    '''StartleMonsToughAppeal''',
    '''MakeFollowingMonNervous''',
    '''MakeFollowingMonsNervous''',
    '''WorsenConditionOfPrevMons''',
    '''BadlyStartlesMonsInGoodCondition''',
    '''BetterIfFirst''',
    '''BetterIfLast''',
    '''AppealAsGoodAsPrevOnes''',
    '''AppealAsGoodAsPrevOne''',
    '''BetterWhenLater''',
    '''QualityDependsOnTiming''',
    '''BetterIfSameType''',
    '''BetterIfDiffType''',
    '''AffectedByPrevAppeal''',
    '''ImproveConditionPreventNervousness''',
    '''BetterWithGoodCondition''',
    '''NextAppealEarlier''',
    '''NextAppealLater''',
    '''MakeScramblingTurnOrderEasier''',
    '''ScrambleNextTurnOrder''',
    '''ExciteAudienceInAnyContest''',
    '''BadlyStartleMonsWithGoodAppeals''',
    '''BettenWhenAudienceExcited''',
    '''DontExciteAudience''',
]

[[List]]
Name = '''contesteffects'''
0 = [
   '''Appeal''',
   '''AvoidStartle''',
   '''StartleMon''',
   '''StartleMons''',
   '''Worsen''',
   '''SpecialAppeal''',
   '''TurnOrder''',
]

[[List]]
Name = '''contestcombostarter'''
0 = [
    '''-''',
    '''Rain Dance''',
    '''Rage''',
    '''Focus Energy''',
    '''Hypnosis''',
    '''Endure''',
    '''Horn Attack''',
    '''Swords Dance''',
    '''Stockpile''',
    '''Sunny Day''',
    '''Rest''',
    '''Vice Grip''',
    '''Defense Curl''',
    '''Charge''',
    '''Rock Throw''',
    '''Yawn''',
    '''Scary Face''',
    '''Powder Snow''',
    '''Lock On''',
    '''Soft Boiled''',
    '''Mean Look''',
    '''Scratch''',
    '''Growth''',
    '''Hail''',
    '''Sandstorm''',
    '''Belly Drum''',
    '''Mind Reader''',
    '''Dragon Breath''',
    '''Dragon Rage''',
    '''Dragon Dance''',
    '''Serf''',
    '''Dife''',
    '''String Shot''',
    '''Leer''',
    '''Taunt''',
    '''Charm''',
    '''Harden''',
    '''Sing''',
    '''Earthquake''',
    '''DoubleTeam''',
    '''Curse''',
    '''SweetScent''',
    '''Sludge''',
    '''Sludge Bomb''',
    '''Thunder Punch''',
    '''Fire Punch''',
    '''Ice Punch''',
    '''Peck''',
    '''Metal Sound''',
    '''Mud Sport''',
    '''Water Sport''',
    '''Bone Club''',
    '''Bonemerang''',
    '''Bone Rush''',
    '''Sand Attack''',
    '''Mud Slap''',
    '''Fake Out''',
    '''Psychic''',
    '''Kinesis''',
    '''Confusion''',
    '''Pound''',
    '''Smog''',
    '''Calm Mind''',
]

[[List]]
Name = '''moveeffectoptions'''
0 = [
   '''None''',
   '''SleepPrimary''',
   '''PoisonHitChance''',
   '''HealHalfDamage''',
   '''BurnHitChance''',
   '''FreezeHitChance''',
   '''ParalyzeHitChance''',
   '''SelfKOAndAttack''',
   '''HealHalfIfOpponentSleeping''',
   '''RepeatTargetMove''',
   '''RaiseAttack1Primary''',
   '''RaiseDefense1Primary''',
   '''Unused0C''',
   '''RaiseSpAttack1Primary''',
   '''Unused0E''',
   '''Unused0F''',
   '''RaiseEvasiveness1Primary''',
   '''NeverMiss''',
   '''LowerAttack1Primary''',
   '''LowerDefense1Primary''',
   '''LowerSpeed1Primary''',
   '''Unused15''',
   '''Unused16''',
   '''LowerAccuracy1Primary''',
   '''LowerEvasion1Primary''',
   '''RemoveStateChanges''',
   '''Bide''',
   '''2to3turnsThenConfused''',
   '''OpponentSwitch''',
   '''2to5hits''',
   '''ChangeTypeToFriendlyMove''',
   '''Flinch''',
   '''HealHalfSelf''',
   '''BadPoisonPrimary''',
   '''Money''',
   '''RaiseSpDefense2Wall''',
   '''ParalyzeBurnFreeze''',
   '''Rest''',
   '''OHKO''',
   '''2turnHighCrit''',
   '''HalfDamage''',
   '''40Damage''',
   '''2to5turnTrap''',
   '''HighCrit''',
   '''2hits''',
   '''MissHurtSelf''',
   '''PreventStatReduction''',
   '''RaiseCriticalRate''',
   '''25Recoil''',
   '''ConfusionPrimary''',
   '''RaiseAttack2Primary''',
   '''RaiseDefense2Primary''',
   '''RaiseSpeed2Primary''',
   '''RaiseSpAttack2Primary''',
   '''RaiseSpDefense2Primary''',
   '''Unused37''',
   '''Unused38''',
   '''Transform''',
   '''LowerAttack2Primary''',
   '''LowerDefense2Primary''',
   '''LowerSpeed2Primary''',
   '''Unused3D''',
   '''LowerSpDefense2Primary''',
   '''Unused3F''',
   '''Unused40''',
   '''RaiseDefense2Wall''',
   '''PoisonPrimary''',
   '''ParalyzePrimary''',
   '''LowerAttack1HitChance''',
   '''LowerDefense1HitChance''',
   '''LowerSpeed1HitChance''',
   '''LowerSpAttack1HitChance''',
   '''LowerSpDefense1HitChance''',
   '''LowerAccuracy1HitChance''',
   '''Unused4A''',
   '''2turnHighCritFlinch''',
   '''ConfusionHitChance''',
   '''2hitsPoisonHitChance''',
   '''NeverMissMoveLast''',
   '''Substitute''',
   '''SkipNextTurn''',
   '''RaiseAttack1IfDamaged''',
   '''Mimic''',
   '''RandomMove''',
   '''SeedOpponent''',
   '''Splash''',
   '''Disable''',
   '''DamageBasedOnLevel''',
   '''DamageRandom''',
   '''DoubleBackPhysicalDamage''',
   '''OpponentRepeatMoveFor2to6turns''',
   '''PainSplit''',
   '''WhileSleepingAndFlinch''',
   '''ChangeTypeToResistPreviousHit''',
   '''NextAttackHits''',
   '''Sketch''',
   '''Unused60''',
   '''SleepTalk''',
   '''DestinyBond''',
   '''StrengthDependsOnHealth''',
   '''ReducePP''',
   '''NeverKOTarget''',
   '''HealPartyStatus''',
   '''NormalPlusPriority''',
   '''3turnTripleHit''',
   '''StealItem''',
   '''NoSwitch''',
   '''Nightmare''',
   '''RaiseEvasivenessAndBecomeSmaller''',
   '''Curse''',
   '''Unused6E''',
   '''EvadeNextAttack''',
   '''Spikes''',
   '''TargetCannnotRaiseEvasion''',
   '''PerishSong''',
   '''Sand5Turns''',
   '''Endure''',
   '''5turnsUntilMiss''',
   '''ConfuseAndRaiseAttack2''',
   '''GetStrongerEachHit''',
   '''Attract''',
   '''StrongerWithFriendship''',
   '''Present''',
   '''WeakerWithFriendship''',
   '''PreventStatus5Turns''',
   '''BurnDefrost''',
   '''Magnitude''',
   '''BatonPass''',
   '''DoublePowerIfOpponentSwitching''',
   '''RemoveBindSeedSpikes''',
   '''20Damage''',
   '''Unused83''',
   '''MorningSun''',
   '''Synthesis''',
   '''Moonlight''',
   '''HiddenPower''',
   '''Rain5turns''',
   '''Sun5turns''',
   '''RaiseDefense1HitChance''',
   '''RaiseAttack1HitChance''',
   '''RaiseAllStats1HitChance''',
   '''Unused8D''',
   '''HalfHealthToRaiseAttackMax''',
   '''CopyTargetStatChangesPrimary''',
   '''DoubleBackSpecialDamage''',
   '''RaiseDefenseThenAttackTurn2''',
   '''FlinchAndDoubleDamageToFly''',
   '''DoubleDamageToDig''',
   '''DamageIn2Turns''',
   '''DoubleDamageToFly''',
   '''FlinchAndDoubleDamageToMinimize''',
   '''ChargeFirstTurn''',
   '''ParalyzeAndIncreaseAccuracyInRain''',
   '''Escape''',
   '''DamageBasedOnPartySize''',
   '''2turn''',
   '''RaiseDefenseAndImproveRollingMoves''',
   '''RestoreHPOrAllyInField''',
   '''MoveFirstFlinchOnlyWorksTurn1''',
   '''2to5turnsAndAllNoSleep''',
   '''Stockpile''',
   '''Spit Up''',
   '''Swallow''',
   '''UnusedA3''',
   '''Hail5turns''',
   '''Torment''',
   '''ConfuseAndRaiseSpAttack2''',
   '''BurnPrimary''',
   '''SelfKOLowerAttack2SpAttack2''',
   '''DoubleDamageIfSelfStatus''',
   '''SelfFlinchIfHit''',
   '''DoubleDamageToParalyzeAndHealParalyze''',
   '''ForceFoesTargetUser''',
   '''NaturePower''',
   '''BoostNextElectricMove''',
   '''Taunt''',
   '''BoostAllyPower''',
   '''TradeHeldItems''',
   '''CopyAbility''',
   '''HealHalfNextTurn''',
   '''UseAllyMove''',
   '''Ingrain''',
   '''LowerSelfAttack1Defense1''',
   '''ReflectStatusMoves''',
   '''Recycle''',
   '''DoubleDamageIfHitThisTurn''',
   '''BreakWall''',
   '''Yawn''',
   '''KnockOff''',
   '''TargetHPEqualUser''',
   '''DamageBasedOnHighRemainingHealth''',
   '''SwapAbilityWithTarget''',
   '''Imprison''',
   '''HealSelfStatus''',
   '''Grudge''',
   '''Snatch''',
   '''DamageBasedOnTargetWeight''',
   '''SecondEffectBasedOnTerrain''',
   '''33Recoil''',
   '''ConfuseAllPokemon''',
   '''HighCritBurn''',
   '''MudSport''',
   '''BadPoisonHitChance''',
   '''WeatherBall''',
   '''LowerSpAttack2Self''',
   '''LowerAttack1Defense1Primary''',
   '''RaiseDefense1SpDefense1''',
   '''CanDamageFly''',
   '''RaiseAttack1Defense1Primary''',
   '''HighCritPoison''',
   '''WaterSport''',
   '''RaiseSpAttack1SpDefense1Primary''',
   '''RaiseAttack1Speed1Primary''',
   '''ChangetypeFromTerrain''',
]

[[List]]
Name = '''moveinfo'''
0 = [
   '''Makes Contact''',
   '''Affected by Protect''',
   '''Affected by Magic Coat''',
   '''Affected by Snatch''',
   '''Affected by Mirror Move''',
   '''Affected by King's Rock''',
]

[[List]]
Name = '''holdeffects'''
0 = [
   '''None''',
   '''Heal|HP Yellow|Once''',
   '''Remove Paralysis|Once''',
   '''Remove Sleep|Once''',
   '''Remove Poison|Once''',
   '''Remove Burn|Once''',
   '''Remove Freeze|Once''',
   '''Restore PP|Empty|Once''',
   '''Remove Confusion|Once''',
   '''Remove Any Status Condition|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Boost ATK|HP Red|Once''',
   '''Boost DEF|HP Red|Once''',
   '''Boost SPD|HP Red|Once''',
   '''Boost SP.ATK|HP Red|Once''',
   '''Boost SP.DEF|HP Red|Once''',
   '''Boost Crit.Ratio|HP Red|Once''',
   '''Sharp Boost Random Stat|HP Red|Once''',
   '''Reduce Enemy Accuracy''',
   '''Restore Any Stat Loss|Once''',
   '''Macho Brace''',
   '''Exp. Share''',
   '''May Strike First''',
   '''Boost Friendliness''',
   '''Remove Infatuation''',
   '''Choice Band''',
   '''Enemy May Flinch''',
   '''Boost Bug-Type Moves''',
   '''Doubles Battle Money''',
   '''Repels Wild PKMN''',
   '''Soul Dew''',
   '''Boost SP.ATK''',
   '''Boost SP.DEF''',
   '''Flee Any Wild Battle''',
   '''Prevent Evolution''',
   '''May Endure Hit''',
   '''Boost Exp. Gain''',
   '''Boost Crit Ratio''',
   '''Boost Steel-Type Moves''',
   '''Restore Health Each Round''',
   '''No effect''',
   '''Boost SP.ATK For Pikachu''',
   '''Boost Ground-Type Moves''',
   '''Boost Rock-Type Moves''',
   '''Boost Grass-Type Moves''',
   '''Boost Dark-Type Moves''',
   '''Boost Fighting-Type Moves''',
   '''Boost Electric-Type Moves''',
   '''Boost Water-Type Moves''',
   '''Boost Flying-Type Moves''',
   '''Boost Poison-Type Moves''',
   '''Boost Ice-Type Moves''',
   '''Boost Ghost-Type Moves''',
   '''Boost Psychic-Type Moves''',
   '''Boost Fire-Type Moves''',
   '''Boost Dragon-Type Moves''',
   '''Boost Normal-Type Moves''',
   '''Up-Grade''',
   '''Heal When Striking An Enemy''',
   '''Boost Chansey's Crit.Ratio''',
   '''Boost Ditto's DEF''',
   '''Boost Cubone and Marowak ATK''',
   '''Boost Farfetch'd Crit.Ratio''',
]

[[List]]
Name = '''contestPokemonFlags'''
0 = [
    '''whichRankHigh''',
    '''whichRankLow''',
    '''Cool''',
    '''Beauty''',
    '''Cute''',
    '''Smart''',
    '''Tough''',
]

[[List]]
Name = '''owfootprints'''
0 = [
    '''None''',
    '''Feet''',
    '''Bike''',
]

[[List]]
Name = '''movetarget'''
0 = [
   '''RecentAttacker''',
   '''UserOrSelected''',
   '''Random''',
   '''Both''',
   '''Self''',
   '''Everyone''',
   '''Hazard''',
]

[[List]]
Name = '''trainerStructType'''
0 = [
    '''Normal''',
    '''Moves''',
    '''Items''',
    '''Both''',
]

[[List]]
Name = '''decorpermissions'''
0 = [
   '''Normal''',
   '''Put On Floor''',
   '''Object''',
   '''Place On Wall''',
   '''Doll or Cushion''',
]

[[List]]
Name = '''decorcategory'''
0 = [
   '''Desk''',
   '''Chair''',
   '''Plant''',
   '''Unique''',
   '''Mat''',
   '''Poster''',
   '''Doll''',
   '''Cushion''',
]

[[List]]
Name = '''decorshape'''
0 = [
   '''1x1''',
   '''2x1''',
   '''unused''',
   '''1x1t''',
   '''2x2p''',
   '''1x1p''',
   '''unused''',
   '''3x1''',
   '''2x2''',
   '''3x2''',
]

[[List]]
Name = '''evolutionmethods'''
0 = [
   '''None''',
   '''Happiness''',
   '''Happy Day''',
   '''Happy Night''',
   '''Level''',
   '''Trade''',
   '''Trade Item''',
   '''Stone''',
   '''Level High Attack''',
   '''Level Attack matches Defense''',
   '''Level High Defense''',
   '''Level Odd Personality''',
   '''Level Even Personality''',
   '''Level And New Pokemon''',
   '''Level But New Pokemon''',
   '''Beauty''',
]

[[List]]
Name = '''evbits'''
0 = [
   '''+1 HP''',
   '''+2 HP''',
   '''+1 Attack''',
   '''+2 Attack''',
   '''+1 Defense''',
   '''+2 Defense''',
   '''+1 Speed''',
   '''+2 Speed''',
   '''+1 Sp Attack''',
   '''+2 Sp Attack''',
   '''+1 Sp Defense''',
   '''+2 Sp Defense''',
]

[[List]]
Name = '''battletowerEvFlags'''
0 = [
    '''Hp''',
    '''Attack''',
    '''Defense''',
    '''Speed''',
    '''SpAttack''',
    '''SpDefense''',
]

[[List]]
Name = '''traineraibits'''
0 = [
   '''CheckBadMove''',
   '''TryToKO''',
   '''CheckViability''',
   '''SetupFirstTurn''',
   '''Risky''',
   '''PreferStrongestMove''',
   '''PreferBatonPass''',
   '''DoubleBattle''',
   '''HPAware''',
   '''Unknown''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Roaming''',
   '''Safari''',
   '''FirstBattle''',
]

[[List]]
Name = '''script_compare'''
0 = [
    '''<''',
    '''=''',
    '''>''',
    '''<=''',
    '''>=''',
    '''!=''',
]

[[List]]
Name = '''battle_compare'''
0 = [
    '''=''',
    '''!=''',
    '''>''',
    '''<''',
    '''&''',
    '''&~''',
]

[[List]]
Name = '''catchmap_shape'''
0 = [
    '''small''',
    '''wide''',
    '''tall''',
    '''wider''',
    '''taller''',
    '''widest''',
    '''tallest''',
]

[[List]]
Name = '''mapnamepopuptheme'''
0 = [
    '''wood''',
    '''marble''',
    '''stone''',
    '''brick''',
    '''underwater''',
    '''stone2''',
]

[[List]]
Name = '''trainergender'''
0 = [
    '''male''',
    '''female''',
]

[[List]]
Name = '''doublebattleflag'''
0 = [
   '''Single''',
   '''Double''',
]

[[List]]
Name = '''songloopoptions'''
0 = [
    '''playOnce''',
    '''loop''',
]

[[List]]
Name = '''genderratiovalues''' 
0 = '''100% Male'''
31 = '''87% Male'''
63 = '''75% Male'''
89 = '''65% Male'''
127 = '''50% Male & 50% Female'''
165 = '''65% Female'''
181 = '''75% Female'''
223 = '''87% Female'''
254 = '''100% Female'''
255 = '''Genderless'''

[[List]]
Name = '''statusanimations'''
0 = [
   '''Poison''',
   '''Confusion''',
   '''Burn''',
   '''Infatuation''',
   '''Sleep''',
   '''Paralysis''',
   '''Freeze''',
   '''Curse''',
   '''Nightmare''',
]

# This item list isn't actually used... it works for most items, but for pokeball items, the 'type' list means something totally different.
[[List]]
Name = '''itemtype'''
0 = [
    '''Mail''',
    '''Party_Menu''',
    '''Field''',
    '''PokeBlock_Case''',
    '''Bag_Menu''',
]

[[List]]
Name = '''varmacros'''
32780 = [
   '''Facing''',
   '''Ans''',
   '''ItemID''',
   '''LastTalked''',
   '''ContestRank''',
   '''ContestCategory''',
   '''MonBoxID''',
   '''MonBoxPosition''',
]
