[[NamedAnchors]]
Name = '''data.header.title'''
Address = 0x0000A0
Format = '''`asc`12'''

[[NamedAnchors]]
Name = '''data.header.gamecode'''
Address = 0x0000AC
Format = '''`asc`4'''

[[NamedAnchors]]
Name = '''data.header.makercode'''
Address = 0x0000B0
Format = '''`asc`2'''

[[List]]
Name = '''egggroups'''
0 = [
   '''None''',
   '''Monster''',
   '''Water1''',
   '''Bug''',
   '''Flying''',
   '''Field''',
   '''Fairy''',
   '''Grass''',
   '''Human-Like''',
   '''Water3''',
   '''Mineral''',
   '''Amorphous''',
   '''Water2''',
   '''Ditton''',
   '''Dragon''',
   '''Undiscovered''',
]

[[List]]
Name = '''moveeffectoptions'''
0 = [
   '''None''',
   '''SleepPrimary''',
   '''Poison''',
   '''HealHalf''',
   '''Burn''',
   '''Freeze''',
   '''Paralyze''',
   '''SelfKO''',
   '''HealHalfIfOpponentSleeping''',
   '''RepeatFoeMove''',
   '''RaiseAttackPrimary''',
   '''RaiseDefensePrimary''',
   '''???RaiseSpeedPrimary???''',
   '''RaiseSpAttackPrimary''',
   '''unknown1''',
   '''???RaiseAccuracyPrimary???''',
   '''RaiseEvasivenessPrimary''',
   '''NeverMiss''',
   '''LowerAttackPrimary''',
   '''LowerDefensePrimary''',
   '''LowerSpeedPrimary''',
   '''???LowerAttackSpAttackPrimary???''',
   '''unknown2''',
   '''LowerAccuracyPrimary''',
   '''LowerEvasionPrimary''',
   '''RemoveStateChanges''',
   '''Bide''',
   '''2to3turnsThenConfused''',
   '''OpponentSwitch''',
   '''2to5hits''',
   '''ChangeTypeToFriendlyMove''',
   '''Flinch''',
   '''Recover''',
   '''BadPoisonPrimary''',
   '''Money''',
   '''RaiseSpDef2Wall''',
   '''ParalyzeBurnFreeze''',
   '''Rest''',
   '''OHKO''',
   '''2turnHighCrit''',
   '''HalfDamage''',
   '''20Damage''',
   '''2to5turnTrap''',
   '''HighCrit''',
   '''2hits''',
   '''MissHurtSelf''',
   '''PreventStatReduction''',
   '''RaiseCriticalRate''',
   '''25Recoil''',
   '''ConfusionPrimary''',
   '''RaiseAttack2Primary''',
   '''RaiseDefense2Primary''',
   '''RaiseSpeed2Primary''',
   '''RaiseSpAtk2Primary''',
   '''RaiseSpDef2Primary''',
   '''???RaiseAccuracy2Primary???''',
   '''???RaiseEvasiveness2Primary???''',
   '''Transform''',
   '''LowerAttack2Primary''',
   '''LowerDefense2Primary''',
   '''LowerSpeed2Primary''',
   '''???LowerSpAtk2Primary???''',
   '''LowerSpDef2Primary''',
   '''???''',
   '''????''',
   '''RaiseDefense2Wall''',
   '''PoisonPrimary''',
   '''ParalyzePrimary''',
   '''LowerAttack''',
   '''LowerDefense''',
   '''LowerSpeed''',
   '''LowerSpAtk''',
   '''LowerSpDef''',
   '''LowerAccuracy''',
   '''?????''',
   '''2turnHighCritFlinch''',
   '''Confusion''',
   '''2hitsPoison''',
   '''NeverMiss(VitalThrow)''',
   '''Substitute''',
   '''SkipNextTurn''',
   '''StrongerForLessHealth''',
   '''Mimic''',
   '''RandomMove''',
   '''SeedOpponent''',
   '''Splash''',
   '''Disable''',
   '''DamageBasedOnLevel''',
   '''DamageRandom''',
   '''DoublePhysicalDamage''',
   '''OpponentRepeatMoveFor2to6turns''',
   '''PainSplit''',
   '''WhileSleepingFlinch''',
   '''ChangeTypeToResistPreviousHit''',
   '''NextAttackHits''',
   '''Sketch''',
   '''??????''',
   '''SleepTalk''',
   '''DestinyBond''',
   '''StrengthDependsOnHealth''',
   '''ReducePP''',
   '''FalseSwipe''',
   '''HealPartyStatus''',
   '''NormalPlusPriority''',
   '''3turnTripleHit''',
   '''StealItem''',
   '''NoSwitch''',
   '''Nightmare''',
   '''RaiseEvasivenessAndBecomeSmaller''',
   '''Curse''',
   '''??''',
   '''EvadeNextAttack''',
   '''Spikes''',
   '''FoeCannnotRaiseEvasion''',
   '''PerishSong''',
   '''Sandstorm''',
   '''Endure''',
   '''5turnsUntilMiss''',
   '''ConfuseAndRaiseAttack2''',
   '''GetStrongerEachHit''',
   '''Attract''',
   '''StrongerWithFriendship''',
   '''Present''',
   '''WeakerWithFriendship''',
   '''PreventStatus5Turns''',
   '''BurnDefrost''',
   '''Magnitude''',
   '''BatonPass''',
   '''DoublePowerIfOpponentSwitching''',
   '''RemoveBindSeedSpikes''',
   '''20Damage''',
   '''???????''',
   '''MorningSun''',
   '''Synthesis''',
   '''Moonlight''',
   '''HiddenPower''',
   '''Rain5turns''',
   '''Sun5turns''',
   '''RaiseDefense''',
   '''RaiseAttack''',
   '''RaiseAllStats''',
   '''????????''',
   '''HalfHealthToRaiseAttack6''',
   '''CopyFoeStatChangesPrimary''',
   '''DoubleSpecialDamage''',
   '''RaiseDefenseThenAttackTurn2''',
   '''FlinchAndDoubleDamageToFly''',
   '''DoubleDamageToDig''',
   '''DamageIn2Turns''',
   '''DoubleDamageToFly''',
   '''FlinchAndDoubleDamageToMinimize''',
   '''ChargeFirstTurn''',
   '''ParalyzeAndIncreaseAccuracyInRain''',
   '''Escape''',
   '''DamageBasedOnPartySize''',
   '''2turn''',
   '''RaiseDefenseAndImproveRollingMoves''',
   '''RecoverOrFriend''',
   '''OnlyWorksOnce''',
   '''2to5turnsNoSleep''',
   '''Stockpile''',
   '''Spit Up''',
   '''Swallow''',
   '''?????????''',
   '''Hail5turns''',
   '''Torment''',
   '''ConfuseAndRaiseSpAtk2''',
   '''BurnPrimary''',
   '''SelfKOLowerAtkSpAtk2''',
   '''DoubleDamageIfStatus''',
   '''SelfFlinchIfHit''',
   '''DoubleDamageToParalyzeAndHealParalyze''',
   '''ForceFoesAttackMe''',
   '''NaturePower''',
   '''BoostNextElectricMove''',
   '''Taunt''',
   '''BoostAllyPower''',
   '''TradeHeldItems''',
   '''CopyAbility''',
   '''HealHalfNextTurn''',
   '''UseAllyMove''',
   '''Ingrain''',
   '''LowerSelfAtkDef''',
   '''ReflectStatusMoves''',
   '''Recycle''',
   '''DoubleDamageIfHitThisTurn''',
   '''BreakWall''',
   '''Yawn''',
   '''KnockOff''',
   '''Endeavor''',
   '''DamageBasedOnHighRemainingHealth''',
   '''SkillSwap''',
   '''Imprison''',
   '''HealSelfStatus''',
   '''Grudge''',
   '''Snatch''',
   '''DamageBasedOnWeight''',
   '''SecondEffectBasedOnTerrain''',
   '''33Recoil''',
   '''ConfuseAllPokemon''',
   '''HighCritBurn''',
   '''MudSport''',
   '''BadPoison''',
   '''WeatherBall''',
   '''LowerSpAtk2Self''',
   '''LowerAttackDefensePrimary''',
   '''RaiseDefenseSpDef''',
   '''CanDamageFly''',
   '''RaiseAttackDefensePrimary''',
   '''HighCritPoison''',
   '''WaterSport''',
   '''RaiseSpAtkSpDefPrimary''',
   '''RaiseAttackSpeedPrimary''',
   '''ChangetypeFromTerrain''',
]

[[List]]
Name = '''moveinfo'''
0 = [
   '''Makes Contact''',
   '''Affected by Protect''',
   '''Affected by Magic Coat''',
   '''Affected by Snatch''',
   '''Affected by Mirror Move''',
   '''Affected by King's Rock''',
]

[[List]]
Name = '''holdeffects'''
0 = [
   '''None''',
   '''Heal|HP Yellow|Once''',
   '''Remove Paralysis|Once''',
   '''Remove Sleep|Once''',
   '''Remove Poison|Once''',
   '''Remove Burn|Once''',
   '''Remove Freeze|Once''',
   '''Restore PP|Empty|Once''',
   '''Remove Confusion|Once''',
   '''Remove Any Status Condition|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Heal, May Confuse|Once''',
   '''Boost ATK|HP Red|Once''',
   '''Boost DEF|HP Red|Once''',
   '''Boost SPD|HP Red|Once''',
   '''Boost SP.ATK|HP Red|Once''',
   '''Boost SP.DEF|HP Red|Once''',
   '''Boost Crit.Ratio|HP Red|Once''',
   '''Sharp Boost Random Stat|HP Red|Once''',
   '''Reduce Enemy Accuracy''',
   '''Restore Any Stat Loss|Once''',
   '''Macho Brace''',
   '''Exp. Share''',
   '''May Strike First''',
   '''Boost Friendliness''',
   '''Remove Infatuation''',
   '''Choice Band''',
   '''Enemy May Flinch''',
   '''Boost Bug-Type Moves''',
   '''Doubles Battle Money''',
   '''Repels Wild PKMN''',
   '''Soul Dew''',
   '''Boost SP.ATK''',
   '''Boost SP.DEF''',
   '''Flee Any Wild Battle''',
   '''Prevent Evolution''',
   '''May Endure Hit''',
   '''Boost Exp. Gain''',
   '''Boost Crit Ratio''',
   '''Boost Steel-Type Moves''',
   '''Restore Health Each Round''',
   '''No effect''',
   '''Boost SP.ATK For Pikachu''',
   '''Boost Ground-Type Moves''',
   '''Boost Rock-Type Moves''',
   '''Boost Grass-Type Moves''',
   '''Boost Dark-Type Moves''',
   '''Boost Fighting-Type Moves''',
   '''Boost Electric-Type Moves''',
   '''Boost Water-Type Moves''',
   '''Boost Flying-Type Moves''',
   '''Boost Poison-Type Moves''',
   '''Boost Ice-Type Moves''',
   '''Boost Ghost-Type Moves''',
   '''Boost Psychic-Type Moves''',
   '''Boost Fire-Type Moves''',
   '''Boost Dragon-Type Moves''',
   '''Boost Normal-Type Moves''',
   '''Up-Grade''',
   '''Heal When Striking An Enemy''',
   '''Boost Chansey's Crit.Ratio''',
   '''Boost Ditto's DEF''',
   '''Boost Cubone and Marowak ATK''',
   '''Boost Farfetch'd Crit.Ratio''',
]

[[List]]
Name = '''contestPokemonFlags'''
0 = [
    '''whichRankHigh''',
    '''whichRankLow''',
    '''Cool''',
    '''Beauty''',
    '''Cute''',
    '''Smart''',
    '''Tough''',
]

[[List]]
Name = '''owfootprints'''
0 = [
    '''None''',
    '''Feet''',
    '''Bike''',
]

[[List]]
Name = '''movetarget'''
0 = [
   '''RecentAttacker''',
   '''UserOrSelected''',
   '''Random''',
   '''Both''',
   '''Self''',
   '''Everyone''',
   '''Hazard''',
]

[[List]]
Name = '''trainerStructType'''
0 = [
    '''Normal''',
    '''Moves''',
    '''Items''',
    '''Both''',
]

[[List]]
Name = '''decorpermissions'''
0 = [
   '''Normal''',
   '''Put On Floor''',
   '''Object''',
   '''Place On Wall''',
   '''Doll or Cushion''',
]

[[List]]
Name = '''decorcategory'''
0 = [
   '''Desk''',
   '''Chair''',
   '''Plant''',
   '''Unique''',
   '''Mat''',
   '''Poster''',
   '''Doll''',
   '''Cushion''',
]

[[List]]
Name = '''decorshape'''
0 = [
   '''1x1''',
   '''2x1''',
   '''unused''',
   '''1x1t''',
   '''2x2p''',
   '''1x1p''',
   '''unused''',
   '''3x1''',
   '''2x2''',
   '''3x2''',
]

[[List]]
Name = '''evolutionmethods'''
0 = [
   '''None''',
   '''Happiness''',
   '''Happy Day''',
   '''Happy Night''',
   '''Level''',
   '''Trade''',
   '''Trade Item''',
   '''Stone''',
   '''Level High Attack''',
   '''Level Attack matches Defense''',
   '''Level High Defense''',
   '''Level Odd Personality''',
   '''Level Even Personality''',
   '''Level And New Pokemon''',
   '''Level But New Pokemon''',
   '''Beauty''',
]

[[List]]
Name = '''evbits'''
0 = [
   '''+1 HP''',
   '''+2 HP''',
   '''+1 Attack''',
   '''+2 Attack''',
   '''+1 Defense''',
   '''+2 Defense''',
   '''+1 Speed''',
   '''+2 Speed''',
   '''+1 Sp Attack''',
   '''+2 Sp Attack''',
   '''+1 Sp Defense''',
   '''+2 Sp Defense''',
]

[[List]]
Name = '''battletowerEvFlags'''
0 = [
    '''Hp''',
    '''Attack''',
    '''Defense''',
    '''Speed''',
    '''SpAttack''',
    '''SpDefense''',
]

[[List]]
Name = '''traineraibits'''
0 = [
   '''CheckBadMove''',
   '''TryToFaint''',
   '''CheckViability''',
   '''SetupFirstTurn''',
   '''Risky''',
   '''PreferStrongestMove''',
   '''PreferBatonPass''',
   '''DoubleBattle''',
   '''HPAware''',
   '''Unknown''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Ret''',
   '''Roaming''',
   '''Safari''',
   '''FirstBattle''',
]

[[List]]
Name = '''script_compare'''
0 = [
    '''<''',
    '''=''',
    '''>''',
    '''<=''',
    '''>=''',
    '''!=''',
]

[[List]]
Name = '''catchmap_shape'''
0 = [
    '''small''',
    '''wide''',
    '''tall''',
    '''wider''',
    '''taller''',
    '''widest''',
    '''tallest''',
]
