
[[List]]
Name = '''movementtypes'''
0 = [
   '''face_down''',
   '''face_up''',
   '''face_left''',
   '''face_right''',
   '''face_down_fast''',
   '''face_up_fast''',
   '''face_left_fast''',
   '''face_right_fast''',
   '''walk_slowest_down''',
   '''walk_slowest_up''',
   '''walk_slowest_left''',
   '''walk_slowest_right''',
   '''walk_slow_down''',
   '''walk_slow_up''',
   '''walk_slow_left''',
   '''walk_slow_right''',
   '''walk_down''',
   '''walk_up''',
   '''walk_left''',
   '''walk_right''',
   '''jump_2_down''',
   '''jump_2_up''',
   '''jump_2_left''',
   '''jump_2_right''',
   '''delay_1''',
   '''delay_2''',
   '''delay_4''',
   '''delay_8''',
   '''delay_16''',
   '''walk_fast_down''',
   '''walk_fast_up''',
   '''walk_fast_left''',
   '''walk_fast_right''',
   '''walk_in_place_slow_down''',
   '''walk_in_place_slow_up''',
   '''walk_in_place_slow_left''',
   '''walk_in_place_slow_right''',
   '''walk_in_place_down''',
   '''walk_in_place_up''',
   '''walk_in_place_left''',
   '''walk_in_place_right''',
   '''walk_in_place_fast_down''',
   '''walk_in_place_fast_up''',
   '''walk_in_place_fast_left''',
   '''walk_in_place_fast_right''',
   '''walk_in_place_fastest_down''',
   '''walk_in_place_fastest_up''',
   '''walk_in_place_fastest_left''',
   '''walk_in_place_fastest_right''',
   '''face_down_slow''',
   '''face_up_slow''',
   '''face_left_slow''',
   '''face_right_slow''',
   '''walk_fastest_down''',
   '''walk_fastest_up''',
   '''walk_fastest_left''',
   '''walk_fastest_right''',
   '''slide_down''',
   '''slide_up''',
   '''slide_left''',
   '''slide_right''',
   '''player_run_down''',
   '''player_run_up''',
   '''player_run_left''',
   '''player_run_right''',
   '''player_run_down_slow''',
   '''player_run_up_slow''',
   '''player_run_left_slow''',
   '''player_run_right_slow''',
   '''step_45''',
   '''jump_down_run''',
   '''jump_up_run''',
   '''jump_left_run''',
   '''jump_right_run''',
   '''face_player''',
   '''face_away_player''',
   '''lock_facing_direction''',
   '''unlock_facing_direction''',
   '''jump_down''',
   '''jump_up''',
   '''jump_left''',
   '''jump_right''',
   '''jump_in_place_down''',
   '''jump_in_place_up''',
   '''jump_in_place_left''',
   '''jump_in_place_right''',
   '''jump_in_place_down_up''',
   '''jump_in_place_up_down''',
   '''jump_in_place_left_right''',
   '''jump_in_place_right_left''',
   '''face_original_direction''',
   '''nurse_joy_bow''',
   '''enable_jump_landing_ground_effect''',
   '''disable_jump_landing_ground_effect''',
   '''disable_anim''',
   '''restore_anim''',
   '''set_invisible''',
   '''set_visible''',
   '''emote_exclamation_mark''',
   '''emote_question_mark''',
   '''emote_x''',
   '''emote_double_exclamation_mark''',
   '''emote_smile''',
   '''reveal_trainer''',
   '''rock_smash_break''',
   '''cut_tree''',
]

[[List]]
Name = '''songnames'''
0 = [
   '''mus_dummy''',
   '''se_use_item''',
   '''se_pc_login''',
   '''se_pc_off''',
   '''se_pc_on''',
   '''se_select''',
   '''se_win_open''',
   '''se_wall_hit''',
   '''se_rs_door''',
   '''se_exit''',
   '''se_ledge''',
   '''se_bike_bell''',
   '''se_not_effective''',
   '''se_effective''',
   '''se_super_effective''',
   '''se_ball_open''',
   '''se_faint''',
   '''se_flee''',
   '''se_sliding_door''',
   '''se_ship''',
   '''se_bang''',
   '''se_pin''',
   '''se_boo''',
   '''se_ball''',
   '''se_contest_place''',
   '''se_success''',
   '''se_failure''',
   '''se_exp''',
   '''se_bike_hop''',
   '''se_switch''',
   '''se_click''',
   '''se_fu_zaku''',
   '''se_contest_condition_lose''',
   '''se_lavaridge_fall_warp''',
   '''se_ice_stairs''',
   '''se_ice_break''',
   '''se_ice_crack''',
   '''se_fall''',
   '''se_unlock''',
   '''se_warp_in''',
   '''se_warp_out''',
   '''se_repel''',
   '''se_rotating_gate''',
   '''se_truck_move''',
   '''se_truck_stop''',
   '''se_truck_unload''',
   '''se_truck_door''',
   '''se_berry_blender''',
   '''se_save''',
   '''se_ball_bounce_1''',
   '''se_ball_bounce_2''',
   '''se_ball_bounce_3''',
   '''se_ball_bounce_4''',
   '''se_ball_trade''',
   '''se_ball_throw''',
   '''se_note_c''',
   '''se_note_d''',
   '''se_note_e''',
   '''se_note_f''',
   '''se_note_g''',
   '''se_note_a''',
   '''se_note_b''',
   '''se_note_c_high''',
   '''se_puddle''',
   '''se_bridge_walk''',
   '''se_itemfinder''',
   '''se_ding_dong''',
   '''se_balloon_red''',
   '''se_balloon_blue''',
   '''se_balloon_yellow''',
   '''se_breakable_door''',
   '''se_mud_ball''',
   '''se_field_poison''',
   '''se_escalator''',
   '''se_thunderstorm''',
   '''se_thunderstorm_stop''',
   '''se_downpour''',
   '''se_downpour_stop''',
   '''se_rain''',
   '''se_rain_stop''',
   '''se_thunder''',
   '''se_thunder2''',
   '''se_elevator''',
   '''se_low_health''',
   '''se_exp_max''',
   '''se_roulette_ball''',
   '''se_roulette_ball2''',
   '''se_taillow_wing_flap''',
   '''se_rs_shop''',
   '''se_contest_heart''',
   '''se_contest_curtain_rise''',
   '''se_contest_curtain_fall''',
   '''se_contest_icon_change''',
   '''se_contest_icon_clear''',
   '''se_contest_mons_turn''',
   '''se_shiny''',
   '''se_intro_blast''',
   '''se_mugshot''',
   '''se_applause''',
   '''se_vend''',
   '''se_orb''',
   '''se_dex_scroll''',
   '''se_dex_page''',
   '''se_pokenav_on''',
   '''se_pokenav_off''',
   '''se_dex_search''',
   '''se_egg_hatch''',
   '''se_ball_tray_enter''',
   '''se_ball_tray_ball''',
   '''se_ball_tray_exit''',
   '''se_glass_flute''',
   '''se_m_thunderbolt''',
   '''se_m_thunderbolt2''',
   '''se_m_harden''',
   '''se_m_nightmare''',
   '''se_m_vital_throw''',
   '''se_m_vital_throw2''',
   '''se_m_bubble''',
   '''se_m_bubble2''',
   '''se_m_bubble3''',
   '''se_m_rain_dance''',
   '''se_m_cut''',
   '''se_m_string_shot''',
   '''se_m_string_shot2''',
   '''se_m_rock_throw''',
   '''se_m_gust''',
   '''se_m_gust2''',
   '''se_m_double_slap''',
   '''se_m_double_team''',
   '''se_m_razor_wind''',
   '''se_m_icy_wind''',
   '''se_m_thunder_wave''',
   '''se_m_comet_punch''',
   '''se_m_mega_kick''',
   '''se_m_mega_kick2''',
   '''se_m_crabhammer''',
   '''se_m_jump_kick''',
   '''se_m_flame_wheel''',
   '''se_m_flame_wheel2''',
   '''se_m_flamethrower''',
   '''se_m_fire_punch''',
   '''se_m_toxic''',
   '''se_m_sacred_fire''',
   '''se_m_sacred_fire2''',
   '''se_m_ember''',
   '''se_m_take_down''',
   '''se_m_blizzard''',
   '''se_m_blizzard2''',
   '''se_m_scratch''',
   '''se_m_vicegrip''',
   '''se_m_wing_attack''',
   '''se_m_fly''',
   '''se_m_sand_attack''',
   '''se_m_razor_wind2''',
   '''se_m_bite''',
   '''se_m_headbutt''',
   '''se_m_surf''',
   '''se_m_hydro_pump''',
   '''se_m_whirlpool''',
   '''se_m_horn_attack''',
   '''se_m_tail_whip''',
   '''se_m_mist''',
   '''se_m_poison_powder''',
   '''se_m_bind''',
   '''se_m_dragon_rage''',
   '''se_m_sing''',
   '''se_m_perish_song''',
   '''se_m_pay_day''',
   '''se_m_dig''',
   '''se_m_dizzy_punch''',
   '''se_m_self_destruct''',
   '''se_m_explosion''',
   '''se_m_absorb_2''',
   '''se_m_absorb''',
   '''se_m_screech''',
   '''se_m_bubble_beam''',
   '''se_m_bubble_beam2''',
   '''se_m_supersonic''',
   '''se_m_belly_drum''',
   '''se_m_metronome''',
   '''se_m_bonemerang''',
   '''se_m_lick''',
   '''se_m_psybeam''',
   '''se_m_faint_attack''',
   '''se_m_swords_dance''',
   '''se_m_leer''',
   '''se_m_swagger''',
   '''se_m_swagger2''',
   '''se_m_heal_bell''',
   '''se_m_confuse_ray''',
   '''se_m_snore''',
   '''se_m_brick_break''',
   '''se_m_giga_drain''',
   '''se_m_psybeam2''',
   '''se_m_solar_beam''',
   '''se_m_petal_dance''',
   '''se_m_teleport''',
   '''se_m_minimize''',
   '''se_m_sketch''',
   '''se_m_swift''',
   '''se_m_reflect''',
   '''se_m_barrier''',
   '''se_m_detect''',
   '''se_m_lock_on''',
   '''se_m_moonlight''',
   '''se_m_charm''',
   '''se_m_charge''',
   '''se_m_strength''',
   '''se_m_hyper_beam''',
   '''se_m_waterfall''',
   '''se_m_reversal''',
   '''se_m_acid_armor''',
   '''se_m_sandstorm''',
   '''se_m_tri_attack''',
   '''se_m_tri_attack2''',
   '''se_m_encore''',
   '''se_m_encore2''',
   '''se_m_baton_pass''',
   '''se_m_milk_drink''',
   '''se_m_attract''',
   '''se_m_attract2''',
   '''se_m_morning_sun''',
   '''se_m_flatter''',
   '''se_m_sand_tomb''',
   '''se_m_grasswhistle''',
   '''se_m_spit_up''',
   '''se_m_dive''',
   '''se_m_earthquake''',
   '''se_m_twister''',
   '''se_m_sweet_scent''',
   '''se_m_yawn''',
   '''se_m_sky_uppercut''',
   '''se_m_stat_increase''',
   '''se_m_heat_wave''',
   '''se_m_uproar''',
   '''se_m_hail''',
   '''se_m_cosmic_power''',
   '''se_m_teeter_dance''',
   '''se_m_stat_decrease''',
   '''se_m_haze''',
   '''se_m_hyper_beam2''',
   '''se_door''',
   '''se_card_flip''',
   '''se_card_flipping''',
   '''se_card_open''',
   '''se_bag_cursor''',
   '''se_bag_pocket''',
   '''se_ball_click''',
   '''se_shop''',
   '''se_ss_anne_horn''',
   '''se_help_open''',
   '''se_help_close''',
   '''se_help_error''',
   '''se_deoxys_move''',
   '''se_poke_jump_success''',
   '''se_poke_jump_failure''',
   '''mus_heal''',
   '''mus_level_up''',
   '''mus_obtain_item''',
   '''mus_evolved''',
   '''mus_obtain_badge''',
   '''mus_obtain_tmhm''',
   '''mus_obtain_berry''',
   '''mus_evolution_intro''',
   '''mus_evolution''',
   '''mus_rs_vs_gym_leader''',
   '''mus_rs_vs_trainer''',
   '''mus_school''',
   '''mus_slots_jackpot''',
   '''mus_slots_win''',
   '''mus_move_deleted''',
   '''mus_too_bad''',
   '''mus_follow_me''',
   '''mus_game_corner''',
   '''mus_rocket_hideout''',
   '''mus_gym''',
   '''mus_jigglypuff''',
   '''mus_intro_fight''',
   '''mus_title''',
   '''mus_cinnabar''',
   '''mus_lavender''',
   '''mus_heal_unused''',
   '''mus_cycling''',
   '''mus_encounter_rocket''',
   '''mus_encounter_girl''',
   '''mus_encounter_boy''',
   '''mus_hall_of_fame''',
   '''mus_viridian_forest''',
   '''mus_mt_moon''',
   '''mus_poke_mansion''',
   '''mus_credits''',
   '''mus_route1''',
   '''mus_route24''',
   '''mus_route3''',
   '''mus_route11''',
   '''mus_victory_road''',
   '''mus_vs_gym_leader''',
   '''mus_vs_trainer''',
   '''mus_vs_wild''',
   '''mus_vs_champion''',
   '''mus_pallet''',
   '''mus_oak_lab''',
   '''mus_oak''',
   '''mus_poke_center''',
   '''mus_ss_anne''',
   '''mus_surf''',
   '''mus_poke_tower''',
   '''mus_silph''',
   '''mus_fuchsia''',
   '''mus_celadon''',
   '''mus_victory_trainer''',
   '''mus_victory_wild''',
   '''mus_victory_gym_leader''',
   '''mus_vermillion''',
   '''mus_pewter''',
   '''mus_encounter_rival''',
   '''mus_rival_exit''',
   '''mus_dex_rating''',
   '''mus_obtain_key_item''',
   '''mus_caught_intro''',
   '''mus_photo''',
   '''mus_game_freak''',
   '''mus_caught''',
   '''mus_new_game_instruct''',
   '''mus_new_game_intro''',
   '''mus_new_game_exit''',
   '''mus_poke_jump''',
   '''mus_union_room''',
   '''mus_net_center''',
   '''mus_mystery_gift''',
   '''mus_berry_pick''',
   '''mus_sevii_cave''',
   '''mus_teachy_tv_show''',
   '''mus_sevii_route''',
   '''mus_sevii_dungeon''',
   '''mus_sevii_123''',
   '''mus_sevii_45''',
   '''mus_sevii_67''',
   '''mus_poke_flute''',
   '''mus_vs_deoxys''',
   '''mus_vs_mewtwo''',
   '''mus_vs_legend''',
   '''mus_encounter_gym_leader''',
   '''mus_encounter_deoxys''',
   '''mus_trainer_tower''',
   '''mus_slow_pallet''',
   '''mus_teachy_tv_menu''',
]

[[List]]
Name = '''pocketid'''
1 = [
   '''item''',
   '''key''',
   '''ball''',
   '''tm''',
   '''berry'''
]

[[NamedAnchors]]
Name = '''data.header.romname'''
Address = 0x000108
Format = '''`asc`32'''

[[GotoShortcut]]
Name = '''Pokemon'''
Image = '''graphics.pokemon.sprites.front/29/sprite/'''
Destination = '''data.pokemon.stats/1'''

[[GotoShortcut]]
Name = '''Trainers'''
Image = '''graphics.trainers.sprites.front/19/sprite/'''
Destination = '''data.trainers.stats'''

[[GotoShortcut]]
Name = '''Moves'''
Image = '''graphics.moves.tmcase.sprite'''
Destination = '''data.pokemon.moves.stats.battle'''

[[GotoShortcut]]
Name = '''Items'''
Image = '''graphics.items.sprites/13/sprite/'''
Destination = '''data.items.stats'''
