# BPRE1

[[NamedAnchors]]
Name = '''scripts.newgame.starters.left'''
Address = 0x169C2D
Format = '''[species1:data.pokemon.names]scripts.newgame.starters.middle'''

[[NamedAnchors]]
Name = '''scripts.newgame.starters.middle'''
Address = 0x169DFA
Format = '''[species2:data.pokemon.names]1'''

[[NamedAnchors]]
Name = '''scripts.newgame.starters.right'''
Address = 0x169E30
Format = '''[species3:data.pokemon.names]scripts.newgame.starters.middle'''
