# BPGE0

[[NamedAnchors]]
Name = '''scripts.newgame.starters.left'''
Address = 0x169B91
Format = '''[species1:data.pokemon.names]scripts.newgame.starters.middle'''

[[NamedAnchors]]
Name = '''scripts.newgame.starters.middle'''
Address = 0x169D5E
Format = '''[species2:data.pokemon.names]1'''

[[NamedAnchors]]
Name = '''scripts.newgame.starters.right'''
Address = 0x169D94
Format = '''[species3:data.pokemon.names]scripts.newgame.starters.middle'''
