
[[OffsetPointer]]
Address = 0x011524
Offset = 0x000004

[[OffsetPointer]]
Address = 0x0116D4
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03E90C
Offset = 0x000004

[[OffsetPointer]]
Address = 0x03E9B4
Offset = 0x000004

[[OffsetPointer]]
Address = 0x040EF4
Offset = 0x000004

[[OffsetPointer]]
Address = 0x046218
Offset = 0x000011

[[OffsetPointer]]
Address = 0x0462BC
Offset = 0x000011
